# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch

import torch
# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.2717, 0.7657, 0.1770, 0.3543, 0.6244, 0.5569, 0.9696],
        [0.4316, 0.1063, 0.6535, 0.6810, 0.6006, 0.7760, 0.2710],
        [0.3544, 0.5144, 0.9295, 0.5942, 0.2293, 0.6919, 0.2033],
        [0.4722, 0.6647, 0.0646, 0.1257, 0.1331, 0.2332, 0.9593],
        [0.8019, 0.6595, 0.1861, 0.2091, 0.8515, 0.6696, 0.1978],
        [0.5977, 0.6897, 0.9119, 0.7144, 0.3155, 0.1215, 0.2498],
        [0.4599, 0.5614, 0.1273, 0.3471, 0.5129, 0.3563, 0.6847]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
A = torch.rand(1,7)
B = torch.rand(7,1)
# Perform matrix multiplication
torch.matmul(A,B), A @ B


(tensor([[0.9113]]), tensor([[0.9113]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [2]:
# Set manual seed
import torch
random_seed = 42
torch.manual_seed(random_seed)
random = torch.randn(7,7)

torch.manual_seed(random_seed)
random2 = torch.randn(7,7)

random, random2

# Create two random tensors


# Matrix multiply tensors


(tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431],
         [-1.6047, -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594],
         [-0.7688,  0.7624,  1.6423, -0.1596, -0.4974,  0.4396, -0.7581],
         [ 1.0783,  0.8008,  1.6806,  1.2791,  1.2964,  0.6105,  1.3347],
         [-0.2316,  0.0418, -0.2516,  0.8599, -1.3847, -0.6581,  0.0780],
         [ 0.5258, -0.4880,  1.1914, -0.8140, -0.7360, -0.8371,  0.0360],
         [-0.0635,  0.6756, -0.0978,  1.8446, -1.1845,  1.3835, -1.2024]]),
 tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431],
         [-1.6047, -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594],
         [-0.7688,  0.7624,  1.6423, -0.1596, -0.4974,  0.4396, -0.7581],
         [ 1.0783,  0.8008,  1.6806,  1.2791,  1.2964,  0.6105,  1.3347],
         [-0.2316,  0.0418, -0.2516,  0.8599, -1.3847, -0.6581,  0.0780],
         [ 0.5258, -0.4880,  1.1914, -0.8140, -0.7360, -0.8371,  0.0360],
         [-0.0635,  0.6756, -0.0978,

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed

random_seed = 42
torch.cuda.manual_seed(random_seed)
# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device is: {device} ")
# Create two random tensors on GPU
tensor_A = torch.rand(2,4).to(device)
tensor_B = torch.rand(2,4).to(device)
tensor_A, tensor_B

Device is: cuda 


(tensor([[0.2849, 0.4452, 0.1258, 0.9554],
         [0.1330, 0.7672, 0.6757, 0.6625]], device='cuda:0'),
 tensor([[0.2297, 0.9545, 0.6099, 0.5643],
         [0.0594, 0.7099, 0.4250, 0.2709]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape

(tensor([[1.1062, 0.6453],
         [1.5488, 1.0192]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
torch.max(tensor_A), torch.min(tensor_B)
# Find min


(tensor(0.9554, device='cuda:0'), tensor(0.0594, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
torch.argmax(tensor_A), torch.argmin(tensor_B)

# Find arg min


(tensor(3, device='cuda:0'), tensor(4, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed

torch.manual_seed(42)

# Create random tensor
A = torch.rand(1,1,2,10)
A, A.shape
# Remove single dimensions
B = A.squeeze()
B, B.shape
#

# Remove single dimensions


# Print out tensors and their shapes


(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
          0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666,
          0.6274]]),
 torch.Size([2, 10]))